### PR TITLE
feat: Add support for creating private services with VPC ingress connection

### PR DESCRIPTION
**Pull request by bryantbiggs**
## Description
- Add support for creating private services with VPC ingress connection
	- Ref: https://github.com/hashicorp/terraform-provider-aws/pull/27600

## Motivation and Context
- Allows users to create private services to be used within a VPC and not publicly accessible

## Breaking Changes
- No

## How Has This Been Tested?
- [x] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- [x] I have tested and validated these changes using one or more of the provided `examples/*` projects
- [x] I have executed `pre-commit run -a` on my pull request

### CODE REVIEW

**Comment by bryantbiggs** [comment]
Ps - might need to enable branch protection to require a review on this repo

**Review by antonbabenko — APPROVED** [review]
👍

**Comment by antonbabenko** [comment]
> Ps - might need to enable branch protection to require a review on this repo

Agree, I will fix it on Monday for some newer repos, too.

**Comment by antonbabenko** [comment]
This PR is included in version 1.1.0 :tada:

**Pull request merged**
